import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { createElement } from 'react';
import { render, cleanup, fireEvent, screen, act } from '@testing-library/react';
import { TopBar } from '@/ui/components/TopBar';
import { LeftPanel } from '@/ui/panels/LeftPanel';
import { GuidedStepCard } from '@/ui/guided/GuidedStepCard';
import { DiagramCanvas } from '@/ui/components/DiagramCanvas';
import { ResponsiveShell } from '@/ui/shell/ResponsiveShell';
import { useEditorStore, useGuidedStore } from '@/state';
import {
  grammarHighlightGuides,
  visibleGrammarHighlightGuides,
  getGuide,
} from '@/data/grammarHighlights';
import { GUIDED_HIGHLIGHT_COLORS } from '@/ui/guided/focus';
import { sampleDocuments } from '@/fixtures';

/**
 * Grammar Highlights UI smoke — the entry flow (⋯ menu → intro modal → mode
 * choice), the top-bar Leave button, the curated left-panel library swap, and
 * the step card's term links / navigation. Rendering-level companions to the
 * store tests in guided.test.ts.
 */

function setWidth(px: number) {
  Object.defineProperty(window, 'innerWidth', { value: px, configurable: true, writable: true });
  window.dispatchEvent(new Event('resize'));
}

describe('guided mode UI', () => {
  beforeEach(() => {
    setWidth(1280);
    useEditorStore.getState().setForceDesktop(false);
    useGuidedStore.getState().leave();
    useGuidedStore.setState({ introOpen: false });
    useEditorStore.getState().newDocument('en', 'Guided UI');
    useEditorStore.getState().setAppMode('explore');
  });
  afterEach(cleanup);

  it('offers Guided Exploration… in the ⋯ menu and opens the intro modal', () => {
    render(createElement(TopBar));
    fireEvent.click(screen.getByRole('button', { name: '⋯' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /guided exploration/i }));
    expect(useGuidedStore.getState().introOpen).toBe(true);
    // The modal renders the Greek/English choice.
    expect(screen.getByRole('dialog', { name: /grammar highlights/i })).toBeTruthy();
    expect(screen.getByText(/greek mode/i)).toBeTruthy();
    expect(screen.getByText(/english mode/i)).toBeTruthy();
  });

  it('the intro modal carries the AI-content caution before entering the mode', () => {
    render(createElement(TopBar));
    act(() => useGuidedStore.getState().openIntro());
    // The warning is visible in the launch modal itself, before either mode
    // choice is made.
    expect(screen.getByText(/generated by\s+ai/i)).toBeTruthy();
    expect(screen.getByText(/discernment/i)).toBeTruthy();
    expect(useGuidedStore.getState().active).toBe(false);
  });

  it('has a dedicated Guided launcher button that opens the intro modal', () => {
    render(createElement(TopBar));
    const launch = screen.getByRole('button', { name: /✦ guided/i });
    fireEvent.click(launch);
    expect(useGuidedStore.getState().introOpen).toBe(true);
  });

  it('choosing Greek mode enters guided mode; the launcher toggles to leave', () => {
    render(createElement(TopBar));
    act(() => useGuidedStore.getState().openIntro());
    fireEvent.click(screen.getByText(/greek mode/i));
    expect(useGuidedStore.getState().active).toBe(true);
    expect(useGuidedStore.getState().introOpen).toBe(false);
    // The launcher now reads "Leave guided" and toggles guided mode off.
    const leave = screen.getByRole('button', { name: /leave guided/i });
    fireEvent.click(leave);
    expect(useGuidedStore.getState().active).toBe(false);
  });

  it('replaces the left-panel pickers with the curated guided library', () => {
    useGuidedStore.getState().enter('greek');
    render(createElement(LeftPanel));
    // The curated library label replaces the OT/GNT tabs…
    expect(screen.getByText('Grammar highlights')).toBeTruthy();
    expect(screen.queryByRole('button', { name: 'GNT' })).toBeNull();
    // …the source presents itself as a curated library, not unrestricted SBLGNT…
    expect(screen.getByText(/curated guided passages/i)).toBeTruthy();
    // …every visible entry is an approved guide…
    for (const g of visibleGrammarHighlightGuides) {
      expect(screen.getByText(g.title)).toBeTruthy();
    }
    // …and hidden guides stay registered but never appear in the picker.
    for (const g of grammarHighlightGuides.filter((x) => x.hidden)) {
      expect(screen.queryByText(g.title)).toBeNull();
    }
    // Acts 2:39 was reworked into a discourse guide and un-hidden — it now
    // appears in the visible library again.
    expect(getGuide('guide-acts-2-39')?.hidden).toBeFalsy();
    expect(visibleGrammarHighlightGuides.some((g) => g.id === 'guide-acts-2-39')).toBe(true);
  });

  it('step card renders term links, opens the detail panel, and navigates', () => {
    useGuidedStore.getState().enter('greek');
    render(createElement(GuidedStepCard));
    const guide = grammarHighlightGuides[0]!;
    expect(screen.getByText(`Step 1 of ${guide.steps.length}`)).toBeTruthy();
    // Tap the first inline Greek term link → the detail panel opens with parsing.
    const firstTermId = guide.steps[0]!.body.match(/\[\[([a-zA-Z0-9_-]+)\]\]/)?.[1];
    if (firstTermId) {
      const term = guide.greekTerms.find((t) => t.id === firstTermId)!;
      const links = screen.getAllByRole('button', { name: term.surface });
      fireEvent.click(links[0]!);
      expect(useGuidedStore.getState().selectedGreekTermId).toBe(term.id);
      expect(screen.getByText(term.parsing)).toBeTruthy();
      expect(screen.getByText(term.transliteration)).toBeTruthy();
    }
    // Navigate forward and back.
    fireEvent.click(screen.getByRole('button', { name: /next/i }));
    expect(useGuidedStore.getState().stepIndex).toBe(1);
    expect(screen.getByText(`Step 2 of ${guide.steps.length}`)).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: /back/i }));
    expect(useGuidedStore.getState().stepIndex).toBe(0);
  });

  it('converts [[term]] markers in implication/caution prose, not just the body (Romans 9:6-13 step 1)', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-romans-9-6-13'));
    const { container } = render(createElement(GuidedStepCard));
    // The caution paragraph must show the tappable Greek surface, never the raw marker.
    expect(container.textContent).not.toContain('[[');
    const caution = container.querySelector('.guided-caution');
    expect(caution).toBeTruthy();
    const link = caution!.querySelector<HTMLButtonElement>('.guided-term-link');
    expect(link?.textContent).toBe('ἐκπέπτωκεν');
    fireEvent.click(link!);
    expect(useGuidedStore.getState().selectedGreekTermId).toBe('ekpeptoken');
  });

  it('English display mode appends an inline transliteration gloss to term links; Greek mode does not', () => {
    useGuidedStore.getState().enter('english');
    const guide = grammarHighlightGuides[0]!;
    const stepIdx = guide.steps.findIndex((s) => /\[\[/.test(s.body));
    expect(stepIdx).toBeGreaterThanOrEqual(0);
    act(() => useGuidedStore.getState().setStep(stepIdx));
    const termId = guide.steps[stepIdx]!.body.match(/\[\[([a-zA-Z0-9_-]+)\]\]/)![1]!;
    const term = guide.greekTerms.find((t) => t.id === termId)!;
    const { container, unmount } = render(createElement(GuidedStepCard));
    const links = Array.from(container.querySelectorAll<HTMLButtonElement>('.guided-term-link'));
    const link = links.find((l) => l.textContent?.startsWith(term.surface));
    expect(link).toBeTruthy();
    // "surface (translit…)" — the gloss itself may be elided when the prose
    // already gives the English on the same line, so assert the stable prefix.
    const inline = link!.querySelector('.guided-term-inline-gloss');
    expect(inline?.textContent?.trim().startsWith(`(${term.transliteration}`)).toBe(true);
    // There must be a real space between the surface and the parenthetical —
    // "θεὸς (theos)", never "θεὸς(theos)". The gap lives OUTSIDE the inline-block
    // span (CSS collapses leading whitespace inside one), so assert on the link's
    // full text rather than the span's.
    expect(link!.textContent).toContain(`${term.surface} (${term.transliteration}`);
    unmount();
    // Greek display mode keeps the bare surface — no parenthetical.
    act(() => useGuidedStore.getState().leave());
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().setStep(stepIdx));
    const greek = render(createElement(GuidedStepCard));
    expect(greek.container.querySelector('.guided-term-inline-gloss')).toBeNull();
  });

  it('a step with a contested reference offers "See the alternate reading" and opens the panel', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-romans-9-5'));
    render(createElement(GuidedStepCard));
    const guide = getGuide('guide-romans-9-5')!;
    const contestedIndex = guide.steps.findIndex((s) => s.contested);
    expect(contestedIndex).toBeGreaterThanOrEqual(0);
    // Steps without a contested reference render no affordance.
    expect(screen.queryByRole('button', { name: /see the alternate reading/i })).toBeNull();
    act(() => useGuidedStore.getState().setStep(contestedIndex));
    fireEvent.click(screen.getByRole('button', { name: /see the alternate reading/i }));
    const e = useEditorStore.getState();
    expect(e.contested.showAlternateParsePanel).toBe(true);
    expect(e.contested.selectedContestedIssueId).toBe('iss_rom_9_5_doxology_sblgnt');
    // The christological reading is baked into the single loaded base document
    // (doxology in apposition to Χριστός), so there is no separate on-demand
    // merged base to build — the panel compares against the loaded doc itself.
    const rel = e.doc.syntax.relations.find((r) => r.id === 'disc_r1');
    expect(rel?.headId).toBe('s0_w_n45009005008');
    expect(rel?.type).toBe('apposition');
  });

  it('a stacked step in the Lord\'s-Prayer guide renders both Gospels with highlights on each', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-lords-prayer-bread'));
    const guide = getGuide('guide-lords-prayer-bread')!;
    const stackedIndex = guide.steps.findIndex((s) => s.secondaryPassageId);
    expect(stackedIndex).toBeGreaterThan(0);
    act(() => useGuidedStore.getState().setStep(stackedIndex));
    const { container } = render(createElement(DiagramCanvas));

    // Two Greek diagram papers render: the primary (loaded) passage and the
    // stacked secondary, which is drawn inside its own `.guided-stacked` frame.
    const papers = Array.from(container.querySelectorAll('svg.diagram-paper'));
    expect(papers.length).toBe(2);
    const secondarySvg = papers.find((el) => el.closest('.guided-stacked'));
    const primarySvg = papers.find((el) => !el.closest('.guided-stacked'));
    expect(secondarySvg).toBeTruthy();
    expect(primarySvg).toBeTruthy();
    expect(container.querySelector('.guided-stacked-head')?.textContent).toMatch(/Matthew 6:11/);

    // The parallel imperatives — δίδου (primary, Luke) and δός (secondary,
    // Matthew) — both carry the guided emphasis swash at once.
    const emphasis = GUIDED_HIGHLIGHT_COLORS.emphasized;
    expect(primarySvg!.querySelector(`rect[fill="${emphasis}"]`)).toBeTruthy();
    expect(secondarySvg!.querySelector(`rect[fill="${emphasis}"]`)).toBeTruthy();
  });

  it('wheel/trackpad zoom on the stacked secondary diagram scales it, same as the primary (D1)', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-lords-prayer-bread'));
    const guide = getGuide('guide-lords-prayer-bread')!;
    const stackedIndex = guide.steps.findIndex((s) => s.secondaryPassageId);
    act(() => useGuidedStore.getState().setStep(stackedIndex));
    const { container } = render(createElement(DiagramCanvas));

    const secondarySvg = Array.from(container.querySelectorAll('svg.diagram-paper')).find((el) =>
      el.closest('.guided-stacked'),
    ) as SVGSVGElement;
    expect(secondarySvg).toBeTruthy();
    const scroller = secondarySvg.closest('.vc-frame-scroll') as HTMLElement;
    expect(scroller).toBeTruthy();

    const widthBefore = Number(secondarySvg.getAttribute('width'));
    // Zoom in (negative deltaY, matching a scroll-up / pinch-out gesture) —
    // the same `wheelZoomFactor` math the primary canvas uses.
    act(() => {
      fireEvent.wheel(scroller, { deltaY: -300 });
    });
    const widthAfter = Number(secondarySvg.getAttribute('width'));
    expect(widthAfter).toBeGreaterThan(widthBefore);

    // Zoom back out (positive deltaY) shrinks it again — a real toggle, not a
    // one-way ratchet.
    act(() => {
      fireEvent.wheel(scroller, { deltaY: 300 });
    });
    const widthAfterZoomOut = Number(secondarySvg.getAttribute('width'));
    expect(widthAfterZoomOut).toBeLessThan(widthAfter);
  });

  it('a non-stacked guide renders no secondary frame', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-john-1-1'));
    const { container } = render(createElement(DiagramCanvas));
    expect(container.querySelector('svg.diagram-paper')).toBeTruthy();
    expect(container.querySelector('svg.diagram-paper.hebrew')).toBeNull();
  });

  it('keeps the guided entry points on a mobile viewport (unlike Edit, guided is available everywhere)', () => {
    setWidth(360);
    render(createElement(TopBar));
    // The dedicated launcher…
    expect(screen.getByRole('button', { name: /✦ guided/i })).toBeTruthy();
    // …and the ⋯-menu item are both still reachable on a phone.
    fireEvent.click(screen.getByRole('button', { name: '⋯' }));
    expect(screen.getByRole('menuitem', { name: /guided exploration/i })).toBeTruthy();
  });

  it('the intro modal offers the Greek/English enter choice on mobile too', () => {
    setWidth(360);
    render(createElement(TopBar));
    act(() => useGuidedStore.getState().openIntro());
    expect(screen.getByText(/greek mode/i)).toBeTruthy();
    expect(screen.getByText(/english mode/i)).toBeTruthy();
  });

  it('the store accepts a programmatic enter() on a mobile viewport', () => {
    setWidth(360);
    useGuidedStore.getState().enter('greek');
    expect(useGuidedStore.getState().active).toBe(true);
    // The normal Explore/KR steering happened just as on desktop.
    expect(useEditorStore.getState().appMode).toBe('explore');
    expect(useEditorStore.getState().diagramMode).toBe('kellogg-reed');
  });

  it('force-desktop still counts as desktop: launcher shown and enter() works at a phone width', () => {
    setWidth(360);
    useEditorStore.getState().setForceDesktop(true);
    render(createElement(TopBar));
    expect(screen.getByRole('button', { name: /✦ guided/i })).toBeTruthy();
    useGuidedStore.getState().enter('greek');
    expect(useGuidedStore.getState().active).toBe(true);
  });

  it('keeps both entry points on a desktop viewport', () => {
    setWidth(1280);
    render(createElement(TopBar));
    expect(screen.getByRole('button', { name: /✦ guided/i })).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: '⋯' }));
    expect(screen.getByRole('menuitem', { name: /guided exploration/i })).toBeTruthy();
  });

  it('a contested reference that cannot be resolved renders nothing', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-romans-9-5'));
    const guide = getGuide('guide-romans-9-5')!;
    const contestedIndex = guide.steps.findIndex((s) => s.contested);
    const step = guide.steps[contestedIndex]!;
    const original = step.contested;
    try {
      // Point the step at a nonexistent issue: the card must degrade silently.
      step.contested = { issueId: 'iss_does_not_exist' };
      act(() => useGuidedStore.getState().setStep(contestedIndex));
      render(createElement(GuidedStepCard));
      expect(screen.queryByRole('button', { name: /see the alternate reading/i })).toBeNull();
    } finally {
      step.contested = original;
    }
  });

  it('Back is present, enabled, and carries the visible secondary-button styling on step >= 2', () => {
    useGuidedStore.getState().enter('greek');
    render(createElement(GuidedStepCard));
    // Step 1: Back is present but disabled (the base .btn:disabled muted look).
    const backAtStep1 = screen.getByRole('button', { name: /back/i });
    expect(backAtStep1).toBeTruthy();
    expect(backAtStep1.hasAttribute('disabled')).toBe(true);
    expect(backAtStep1.className).toContain('guided-nav-back');
    // Advance to step 3 — Back must still be IN THE DOM and now enabled, with
    // the same visible-styling class (not the invisible base .btn look).
    fireEvent.click(screen.getByRole('button', { name: /next/i }));
    fireEvent.click(screen.getByRole('button', { name: /next/i }));
    expect(useGuidedStore.getState().stepIndex).toBe(2);
    const backAtStep3 = screen.getByRole('button', { name: /back/i });
    expect(backAtStep3).toBeTruthy();
    expect(backAtStep3.hasAttribute('disabled')).toBe(false);
    expect(backAtStep3.className).toContain('guided-nav-back');
  });

  it('renders the step nav as a pinned footer sibling of the scrollable content, not inline in the flow (D2)', () => {
    useGuidedStore.getState().enter('greek');
    const { container } = render(createElement(GuidedStepCard));
    const card = container.querySelector('.guided-step-card');
    expect(card).toBeTruthy();
    const scrollArea = container.querySelector('.guided-step-card > .guided-step-scroll');
    const nav = container.querySelector('.guided-step-card > .guided-step-nav');
    expect(scrollArea).toBeTruthy();
    expect(nav).toBeTruthy();
    // The nav is a direct sibling AFTER the scroll area (a footer outside the
    // scrollable body), not nested inside it — so it can never scroll away.
    expect(scrollArea!.contains(nav)).toBe(false);
    expect(nav!.compareDocumentPosition(scrollArea!) & Node.DOCUMENT_POSITION_PRECEDING).toBeTruthy();
    // The step's prose lives inside the scrollable area…
    expect(scrollArea!.querySelector('.guided-step-body')).toBeTruthy();
    // …and Back/Next live in the pinned nav, not inside the scroll area.
    expect(scrollArea!.querySelector('.guided-nav-back')).toBeNull();
    expect(nav!.querySelector('.guided-nav-back')).toBeTruthy();
  });

  it('gives guided mode the full viewport width on a narrow real screen (incl. forced desktop)', () => {
    setWidth(390);
    useEditorStore.getState().setForceDesktop(true);
    // Mount BEFORE entering guided mode so the shell's auto-collapse effect
    // sees the false → true transition (matching real usage: the app is
    // already mounted when the reader taps into a guide).
    const { container } = render(createElement(ResponsiveShell));
    act(() => useGuidedStore.getState().enter('greek'));
    // The right-slot step card carries the full-width modifier class …
    const aside = container.querySelector('.guided-aside');
    expect(aside).toBeTruthy();
    expect(aside!.className).toContain('guided-full-width');
    // … and the left sources panel auto-collapsed so it doesn't eat width.
    expect(useEditorStore.getState().leftCollapsed).toBe(true);
    expect(container.querySelector('.panel.left')?.className).toContain('collapsed');
  });

  it('keeps the normal three-column guided look at a real desktop width (no full-width class)', () => {
    setWidth(1280);
    useEditorStore.getState().setForceDesktop(false);
    const { container } = render(createElement(ResponsiveShell));
    act(() => useGuidedStore.getState().enter('greek'));
    const aside = container.querySelector('.guided-aside');
    expect(aside).toBeTruthy();
    expect(aside!.className).not.toContain('guided-full-width');
  });

  it('drops the whole DIAGRAM control bar on a real mobile width while guided', () => {
    setWidth(360);
    useEditorStore.getState().setForceDesktop(false);
    const { container } = render(createElement(ResponsiveShell));
    act(() => useGuidedStore.getState().enter('greek'));
    expect(container.querySelector('.mobile-main .panel-head')).toBeNull();
    // The diagram itself still renders, expanded (no caret left to collapse it).
    expect(container.querySelector('.mobile-main .canvas:not(.collapsed)')).toBeTruthy();
  });

  it('re-expands a diagram collapsed BEFORE guided entry (the caret is hidden with the bar)', () => {
    setWidth(360);
    useEditorStore.getState().setForceDesktop(false);
    const { container } = render(createElement(ResponsiveShell));
    // Collapse the diagram with the panel-head caret while guided is off …
    const caret = container.querySelector<HTMLButtonElement>('.panel-head .collapse-btn, .panel-head button[title="Collapse diagram"]');
    expect(caret).toBeTruthy();
    act(() => caret!.click());
    expect(container.querySelector('.canvas.collapsed')).toBeTruthy();
    // … then enter guided: the bar (and its caret) disappears, so the diagram
    // must be forced open again or the walkthrough would show nothing.
    act(() => useGuidedStore.getState().enter('greek'));
    expect(container.querySelector('.mobile-main .panel-head')).toBeNull();
    expect(container.querySelector('.mobile-main .canvas:not(.collapsed)')).toBeTruthy();
  });

  it('keeps the DIAGRAM control bar for a forced-desktop guided reader at a phone width', () => {
    setWidth(360);
    useEditorStore.getState().setForceDesktop(true);
    const { container } = render(createElement(ResponsiveShell));
    act(() => useGuidedStore.getState().enter('greek'));
    // Forced-desktop renders the desktop branch, so `.panel-head` lives directly
    // under the syntax canvas rather than `.mobile-main`.
    expect(container.querySelector('.panel-head')).toBeTruthy();
  });

  it('collapses the source strip on entering guided mode and restores it on leave', () => {
    // A real doc with tokens so the source strip actually renders (the fresh
    // `newDocument` from beforeEach has none). Retitled so `bookForDoc` finds no
    // matching GNT book and the parallel-BSB fetch effect is a no-op, mirroring
    // `source-strip-zoom.test.tsx`.
    const johnOneOneA = {
      ...sampleDocuments.find((d) => d.id === 'doc_sample_john_1_1a')!,
      title: 'Sample sentence (guided collapse test)',
    };
    useEditorStore.setState({ doc: johnOneOneA, baseDoc: null, selection: {} });
    render(createElement(DiagramCanvas));
    const collapseBtn = () =>
      document.querySelector('.source-bar .collapse-btn') as HTMLButtonElement | null;
    // Not active yet: the strip starts expanded (normal default).
    expect(collapseBtn()?.title).toBe('Hide source text');
    act(() => useGuidedStore.getState().enter('greek'));
    expect(collapseBtn()?.title).toBe('Show source text');
    act(() => useGuidedStore.getState().leave());
    expect(collapseBtn()?.title).toBe('Hide source text');
  });
});
