import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { createElement } from 'react';
import { render, cleanup, fireEvent, screen, act } from '@testing-library/react';
import { TopBar } from '@/ui/components/TopBar';
import { LeftPanel } from '@/ui/panels/LeftPanel';
import { GuidedStepCard } from '@/ui/guided/GuidedStepCard';
import { DiagramCanvas } from '@/ui/components/DiagramCanvas';
import { useEditorStore, useGuidedStore } from '@/state';
import { grammarHighlightGuides, getGuide } from '@/data/grammarHighlights';
import { GUIDED_HIGHLIGHT_COLORS } from '@/ui/guided/focus';

/**
 * Grammar Highlights UI smoke — the entry flow (⋯ menu → intro modal → mode
 * choice), the top-bar Leave button, the curated left-panel library swap, and
 * the step card's term links / navigation. Rendering-level companions to the
 * store tests in guided.test.ts.
 */

describe('guided mode UI', () => {
  beforeEach(() => {
    useGuidedStore.getState().leave();
    useGuidedStore.setState({ introOpen: false });
    useEditorStore.getState().newDocument('en', 'Guided UI');
    useEditorStore.getState().setAppMode('explore');
  });
  afterEach(cleanup);

  it('offers Grammar highlights… in the ⋯ menu and opens the intro modal', () => {
    render(createElement(TopBar));
    fireEvent.click(screen.getByRole('button', { name: '⋯' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /grammar highlights/i }));
    expect(useGuidedStore.getState().introOpen).toBe(true);
    // The modal renders the Greek/English choice.
    expect(screen.getByRole('dialog', { name: /grammar highlights/i })).toBeTruthy();
    expect(screen.getByText(/greek mode/i)).toBeTruthy();
    expect(screen.getByText(/english mode/i)).toBeTruthy();
  });

  it('the intro modal carries the AI-content caution before entering the mode', () => {
    render(createElement(TopBar));
    act(() => useGuidedStore.getState().openIntro());
    // The warning is visible in the launch modal itself, before either mode
    // choice is made.
    expect(screen.getByText(/generated by\s+ai/i)).toBeTruthy();
    expect(screen.getByText(/discernment/i)).toBeTruthy();
    expect(useGuidedStore.getState().active).toBe(false);
  });

  it('has a dedicated Grammar launcher button that opens the intro modal', () => {
    render(createElement(TopBar));
    const launch = screen.getByRole('button', { name: /✦ grammar/i });
    fireEvent.click(launch);
    expect(useGuidedStore.getState().introOpen).toBe(true);
  });

  it('choosing Greek mode enters guided mode; the launcher toggles to leave', () => {
    render(createElement(TopBar));
    act(() => useGuidedStore.getState().openIntro());
    fireEvent.click(screen.getByText(/greek mode/i));
    expect(useGuidedStore.getState().active).toBe(true);
    expect(useGuidedStore.getState().introOpen).toBe(false);
    // The launcher now reads "Leave guided" and toggles guided mode off.
    const leave = screen.getByRole('button', { name: /leave guided/i });
    fireEvent.click(leave);
    expect(useGuidedStore.getState().active).toBe(false);
  });

  it('replaces the left-panel pickers with the curated guided library', () => {
    useGuidedStore.getState().enter('greek');
    render(createElement(LeftPanel));
    // The curated library label replaces the OT/GNT tabs…
    expect(screen.getByText('Grammar highlights')).toBeTruthy();
    expect(screen.queryByRole('button', { name: 'GNT' })).toBeNull();
    // …the source presents itself as a curated library, not unrestricted SBLGNT…
    expect(screen.getByText(/curated guided passages/i)).toBeTruthy();
    // …and every entry is an approved guide.
    for (const g of grammarHighlightGuides) {
      expect(screen.getByText(g.title)).toBeTruthy();
    }
  });

  it('step card renders term links, opens the detail panel, and navigates', () => {
    useGuidedStore.getState().enter('greek');
    render(createElement(GuidedStepCard));
    const guide = grammarHighlightGuides[0]!;
    expect(screen.getByText(`Step 1 of ${guide.steps.length}`)).toBeTruthy();
    // Tap the first inline Greek term link → the detail panel opens with parsing.
    const firstTermId = guide.steps[0]!.body.match(/\[\[([a-zA-Z0-9_-]+)\]\]/)?.[1];
    if (firstTermId) {
      const term = guide.greekTerms.find((t) => t.id === firstTermId)!;
      const links = screen.getAllByRole('button', { name: term.surface });
      fireEvent.click(links[0]!);
      expect(useGuidedStore.getState().selectedGreekTermId).toBe(term.id);
      expect(screen.getByText(term.parsing)).toBeTruthy();
      expect(screen.getByText(term.transliteration)).toBeTruthy();
    }
    // Navigate forward and back.
    fireEvent.click(screen.getByRole('button', { name: /next/i }));
    expect(useGuidedStore.getState().stepIndex).toBe(1);
    expect(screen.getByText(`Step 2 of ${guide.steps.length}`)).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: /back/i }));
    expect(useGuidedStore.getState().stepIndex).toBe(0);
  });

  it('a step with a contested reference offers "See the alternate reading" and opens the panel', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-romans-9-5'));
    render(createElement(GuidedStepCard));
    const guide = getGuide('guide-romans-9-5')!;
    const contestedIndex = guide.steps.findIndex((s) => s.contested);
    expect(contestedIndex).toBeGreaterThanOrEqual(0);
    // Steps without a contested reference render no affordance.
    expect(screen.queryByRole('button', { name: /see the alternate reading/i })).toBeNull();
    act(() => useGuidedStore.getState().setStep(contestedIndex));
    fireEvent.click(screen.getByRole('button', { name: /see the alternate reading/i }));
    const e = useEditorStore.getState();
    expect(e.contested.showAlternateParsePanel).toBe(true);
    expect(e.contested.selectedContestedIssueId).toBe('iss_rom_9_5_doxology_sblgnt');
    // The merged (9:3–5a + 9:5b) contested base was buildable inside guided mode.
    expect(e.contestedBaseDoc).not.toBeNull();
  });

  it('a stacked step renders the secondary Hebrew frame with highlights on both diagrams', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-acts-2-39'));
    const guide = getGuide('guide-acts-2-39')!;
    const stackedIndex = guide.steps.findIndex((s) => s.secondaryPassageId);
    expect(stackedIndex).toBeGreaterThan(0);
    act(() => useGuidedStore.getState().setStep(stackedIndex));
    const { container } = render(createElement(DiagramCanvas));

    // The stacked secondary diagram is a Hebrew (RTL) frame.
    const hebrewSvg = container.querySelector('svg.diagram-paper.hebrew');
    expect(hebrewSvg).toBeTruthy();
    // The primary (Greek) diagram is the non-Hebrew paper.
    const greekSvg = container.querySelector('svg.diagram-paper:not(.hebrew)');
    expect(greekSvg).toBeTruthy();

    // A guided emphasis swash lands on BOTH an Acts word (primary) and a Genesis
    // word (secondary) — one highlight colour, two stacked diagrams.
    const emphasis = GUIDED_HIGHLIGHT_COLORS.emphasized;
    expect(greekSvg!.querySelector(`rect[fill="${emphasis}"]`)).toBeTruthy();
    expect(hebrewSvg!.querySelector(`rect[fill="${emphasis}"]`)).toBeTruthy();
  });

  it('a non-stacked guide renders no secondary frame', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-john-1-1'));
    const { container } = render(createElement(DiagramCanvas));
    expect(container.querySelector('svg.diagram-paper')).toBeTruthy();
    expect(container.querySelector('svg.diagram-paper.hebrew')).toBeNull();
  });

  it('a contested reference that cannot be resolved renders nothing', () => {
    useGuidedStore.getState().enter('greek');
    act(() => useGuidedStore.getState().openGuide('guide-romans-9-5'));
    const guide = getGuide('guide-romans-9-5')!;
    const contestedIndex = guide.steps.findIndex((s) => s.contested);
    const step = guide.steps[contestedIndex]!;
    const original = step.contested;
    try {
      // Point the step at a nonexistent issue: the card must degrade silently.
      step.contested = { issueId: 'iss_does_not_exist' };
      act(() => useGuidedStore.getState().setStep(contestedIndex));
      render(createElement(GuidedStepCard));
      expect(screen.queryByRole('button', { name: /see the alternate reading/i })).toBeNull();
    } finally {
      step.contested = original;
    }
  });
});
