/**
 * guided-text — the shared core behind `npm run guided:text:export` and
 * `npm run guided:text:import`.
 *
 * The Grammar-Highlights (guided mode) prose lives as string literals in the
 * hand-written guide modules under `src/data/guides/*.ts`. This module gives
 * that text a stable, reviewable round-trip:
 *
 *  - `buildGuidedTextExport(guides)` walks every guide and emits ONE Markdown
 *    document containing every reader-facing text field, each between a
 *    `<!-- @field <key> -->` … `<!-- @end -->` marker pair. The key is
 *    `<guideId> :: <path>` where the path addresses the field inside the
 *    guide object literal (steps/terms/arcs by their stable ids, e.g.
 *    `steps[step-word-was-god].body`, `greekTerms[theos].caution`,
 *    `debateSummary.views[0].cautions[1]`).
 *  - `parseGuidedTextMarkdown(md)` reads the (possibly edited) file back into
 *    a key → text map. Everything OUTSIDE marker pairs (headings, labels) is
 *    ignored, so the decorative structure can never corrupt an import.
 *  - `rewriteGuideText(sourceText, guideId, changes)` performs the drop-in
 *    replacement: it resolves each path against the guide module's TypeScript
 *    AST and replaces exactly the matching string literal, leaving ids,
 *    comments, and formatting untouched.
 *
 * NOT exported (by design): ids, token/node/relation focus ids, refs, colors,
 * topics, source ids — everything structural. Only prose a reviewer should
 * touch. Line breaks inside an edited block are collapsed to single spaces on
 * import (`normalizeGuidedText`), so reviewers may hard-wrap text freely.
 */

import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import type { GrammarHighlightGuide } from '../../src/domain/schema/guided.ts';

// ---------------------------------------------------------------------------
// Text normalization
// ---------------------------------------------------------------------------

/** Collapse all whitespace runs (incl. newlines from re-wrapped text) to single spaces. */
export function normalizeGuidedText(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

// ---------------------------------------------------------------------------
// Field enumeration + Markdown serialization (ONE walker for both, so the
// export document and the "current text" map can never drift apart)
// ---------------------------------------------------------------------------

export interface GuidedTextEntry {
  /** Full marker key: `<guideId> :: <path>`. */
  key: string;
  guideId: string;
  /** Path inside the guide object literal (see `parseGuidedPath`). */
  path: string;
  /** Human label shown above the block in the export file. */
  label: string;
  /** The current text, verbatim from the registry. */
  text: string;
}

const SAFE_ID = /^[A-Za-z0-9_-]+$/;

/**
 * Address an array item by its `id` when that id is bracket-safe and unique
 * among its siblings; otherwise fall back to the numeric index.
 */
function itemSelector(items: ReadonlyArray<{ id?: string }>, index: number): string {
  const id = items[index]?.id;
  if (
    typeof id === 'string' &&
    SAFE_ID.test(id) &&
    items.filter((it) => it.id === id).length === 1
  ) {
    return id;
  }
  return String(index);
}

export interface GuidedTextExport {
  markdown: string;
  entries: GuidedTextEntry[];
}

export const GUIDED_TEXT_DEFAULT_FILE = 'guided-text.md';

/** Serialize every guide's prose into the review Markdown + the entry list. */
export function buildGuidedTextExport(
  guides: readonly GrammarHighlightGuide[],
  opts: { generatedNote?: string } = {},
): GuidedTextExport {
  const lines: string[] = [];
  const entries: GuidedTextEntry[] = [];

  const push = (...ls: string[]) => lines.push(...ls);

  push(
    '<!-- ============================================================',
    'GRAMMAR HIGHLIGHTS (guided mode) — TEXT REVIEW FILE',
    '',
    `Generated by \`npm run guided:text:export\`${opts.generatedNote ? ` (${opts.generatedNote})` : ''}.`,
    '',
    'How to use this file:',
    '  1. Edit ONLY the text between `<!-- @field … -->` and `<!-- @end -->`',
    '     markers. Headings and **labels** are decoration — they are ignored',
    '     on import and regenerated on the next export.',
    '  2. Do NOT edit the marker lines themselves (the keys address the exact',
    '     string in the source code).',
    '  3. Line breaks inside a block are collapsed to single spaces on import,',
    '     so you may re-wrap long paragraphs freely.',
    '  4. Keep `[[termId]]` markers intact — they render as tappable',
    '     Greek-term links in the app (the import will refuse an unknown id).',
    '  5. Deleting a whole block (marker lines included) leaves that field',
    '     unchanged. Emptying a block is an error, never a deletion.',
    '  6. Structural data (ids, focus targets, verse refs, colors, topics) is',
    '     deliberately not here — edit the guide modules for that.',
    '',
    'Re-import with:  npm run guided:text:import -- guided-text.md',
    '  (add --dry-run to preview). Then run `npm run guided:check` and',
    '  `npm run test` before committing.',
    '============================================================ -->',
    '',
  );

  for (const guide of guides) {
    const field = (p: string, label: string, text: string | undefined) => {
      if (text === undefined || text === '') return;
      const key = `${guide.id} :: ${p}`;
      entries.push({ key, guideId: guide.id, path: p, label, text });
      push(`**${label}**`, `<!-- @field ${key} -->`, text, '<!-- @end -->', '');
    };

    push('---', '', `# ${guide.title}`, '');
    push(
      `<!-- guide ${guide.id} · ${guide.reference} · ${guide.difficulty}` +
        `${guide.kind === 'discourse' ? ' · discourse guide' : ''}` +
        `${guide.hidden ? ' · HIDDEN (not in the picker)' : ''} -->`,
      '',
    );

    push('## Overview', '');
    field('title', 'Guide title', guide.title);
    field('reference', 'Reference', guide.reference);
    field('summary', 'Picker summary', guide.summary);
    field('devotionalFrame', 'Devotional frame', guide.devotionalFrame);
    field('confessionalFrame', 'Confessional frame', guide.confessionalFrame);

    const debate = guide.debateSummary;
    if (debate) {
      push('## Debate summary (fair-views note)', '');
      field('debateSummary.issue', 'The issue', debate.issue);
      debate.views.forEach((view, vi) => {
        push(`### View ${vi + 1}`, '');
        field(`debateSummary.views[${vi}].label`, `View ${vi + 1} — label`, view.label);
        field(`debateSummary.views[${vi}].summary`, `View ${vi + 1} — summary`, view.summary);
        (view.cautions ?? []).forEach((caution, ci) => {
          field(
            `debateSummary.views[${vi}].cautions[${ci}]`,
            `View ${vi + 1} — caution ${ci + 1}`,
            caution,
          );
        });
      });
      field(
        'debateSummary.grammarOpensQuestionHow',
        'How the grammar opens the question',
        debate.grammarOpensQuestionHow,
      );
    }

    if (guide.steps.length > 0) {
      push('## Steps', '');
      guide.steps.forEach((step, si) => {
        const sel = itemSelector(guide.steps, si);
        push(`### Step ${si + 1} — ${step.title}`, '');
        field(`steps[${sel}].title`, 'Step title', step.title);
        field(`steps[${sel}].body`, 'Body', step.body);
        field(`steps[${sel}].implication`, 'Why it matters', step.implication);
        field(`steps[${sel}].caution`, 'Caution', step.caution);
        field(`steps[${sel}].secondaryTitle`, 'Stacked-frame heading', step.secondaryTitle);
        field(`steps[${sel}].contested.note`, 'Contested-reading lead-in', step.contested?.note);
      });
    }

    if (guide.greekTerms.length > 0) {
      push('## Greek terms', '');
      guide.greekTerms.forEach((term, ti) => {
        const sel = itemSelector(guide.greekTerms, ti);
        push(`### ${term.surface} · ${term.transliteration}`, '');
        field(`greekTerms[${sel}].surface`, 'Surface (must match the token)', term.surface);
        field(`greekTerms[${sel}].transliteration`, 'Transliteration', term.transliteration);
        field(`greekTerms[${sel}].lemma`, 'Lemma', term.lemma);
        field(`greekTerms[${sel}].gloss`, 'Gloss', term.gloss);
        field(`greekTerms[${sel}].parsing`, 'Parsing', term.parsing);
        field(`greekTerms[${sel}].explanation`, 'Explanation', term.explanation);
        field(`greekTerms[${sel}].implication`, 'Implication', term.implication);
        field(`greekTerms[${sel}].caution`, 'Caution', term.caution);
      });
    }

    const disc = guide.discourse;
    if (disc) {
      const rangeLabels = disc.ranges.some((r) => r.label || r.fallback);
      const arcs = disc.seededArcs ?? [];
      if (rangeLabels || arcs.length > 0) {
        push('## Discourse ranges & sample arcs', '');
        disc.ranges.forEach((range, ri) => {
          field(`discourse.ranges[${ri}].label`, `Range ${ri + 1} — section label`, range.label);
          field(
            `discourse.ranges[${ri}].fallback.notice`,
            `Range ${ri + 1} — fallback notice`,
            range.fallback?.notice,
          );
        });
        arcs.forEach((arc, ai) => {
          const sel = itemSelector(arcs, ai);
          field(
            `discourse.seededArcs[${sel}].label`,
            `Arc ${arc.sourceRef} ↔ ${arc.targetRef} — label`,
            arc.label,
          );
          field(
            `discourse.seededArcs[${sel}].notes`,
            `Arc ${arc.sourceRef} ↔ ${arc.targetRef} — notes`,
            arc.notes,
          );
        });
      }
    }
  }

  return { markdown: `${lines.join('\n')}\n`, entries };
}

/** Convenience: the entries for one guide (same enumeration as the export). */
export function collectGuideTextEntries(guide: GrammarHighlightGuide): GuidedTextEntry[] {
  return buildGuidedTextExport([guide]).entries;
}

// ---------------------------------------------------------------------------
// Parsing the (edited) Markdown back
// ---------------------------------------------------------------------------

export interface ParsedGuidedTextBlock {
  key: string;
  /** Raw block text (lines joined by \n, NOT yet normalized). */
  text: string;
  /** 1-based line number of the opening marker, for error messages. */
  line: number;
}

const FIELD_OPEN = /^<!--\s*@field\s+(.+?)\s*-->\s*$/;
const FIELD_CLOSE = /^<!--\s*@end\s*-->\s*$/;

/**
 * Parse an exported (and possibly hand-edited) guided-text Markdown file.
 * Only `@field` / `@end` marker pairs matter; all other lines are ignored.
 * Throws on structural damage (nested/unclosed blocks, duplicate keys) with
 * line-numbered messages.
 */
export function parseGuidedTextMarkdown(markdown: string): Map<string, ParsedGuidedTextBlock> {
  const blocks = new Map<string, ParsedGuidedTextBlock>();
  const lines = markdown.split(/\r?\n/);
  let open: { key: string; line: number; content: string[] } | null = null;

  lines.forEach((rawLine, i) => {
    const lineNo = i + 1;
    const openMatch = FIELD_OPEN.exec(rawLine);
    if (openMatch) {
      if (open) {
        throw new Error(
          `guided-text: line ${lineNo}: new @field block opens before the block from line ${open.line} was closed (missing \`<!-- @end -->\`?)`,
        );
      }
      const key = openMatch[1]!;
      if (blocks.has(key)) {
        throw new Error(
          `guided-text: line ${lineNo}: duplicate key "${key}" (first seen at line ${blocks.get(key)!.line})`,
        );
      }
      open = { key, line: lineNo, content: [] };
      return;
    }
    if (FIELD_CLOSE.test(rawLine)) {
      if (!open) {
        throw new Error(`guided-text: line ${lineNo}: \`<!-- @end -->\` without an open @field block`);
      }
      blocks.set(open.key, { key: open.key, text: open.content.join('\n'), line: open.line });
      open = null;
      return;
    }
    if (open) open.content.push(rawLine);
  });

  if (open !== null) {
    const stillOpen = open as { key: string; line: number };
    throw new Error(
      `guided-text: the @field block for "${stillOpen.key}" (line ${stillOpen.line}) is never closed`,
    );
  }
  return blocks;
}

// ---------------------------------------------------------------------------
// Path addressing (shared by the AST rewriter and the runtime setter)
// ---------------------------------------------------------------------------

export interface GuidedPathSegment {
  name: string;
  /** Array selector: an item id, or a numeric index as a string. */
  selector?: string;
}

export function parseGuidedPath(pathStr: string): GuidedPathSegment[] {
  const segments: string[] = [];
  let current = '';
  let depth = 0;
  for (const ch of pathStr) {
    if (ch === '[') depth++;
    else if (ch === ']') depth--;
    if (ch === '.' && depth === 0) {
      segments.push(current);
      current = '';
      continue;
    }
    current += ch;
  }
  segments.push(current);
  return segments.map((seg) => {
    const m = /^([A-Za-z_$][\w$]*)(?:\[(.+)\])?$/.exec(seg);
    if (!m) throw new Error(`guided-text: malformed path segment "${seg}" in "${pathStr}"`);
    return m[2] === undefined ? { name: m[1]! } : { name: m[1]!, selector: m[2] };
  });
}

const isIndexSelector = (selector: string) => /^\d+$/.test(selector);

/**
 * Set a text field on a PLAIN guide object (a clone of the parsed registry
 * entry) using the same path semantics as the AST rewriter — used by the
 * import script to schema-validate all edits BEFORE any file is written.
 */
export function setGuideTextAtPath(guide: unknown, pathStr: string, text: string): void {
  const segments = parseGuidedPath(pathStr);
  let node: unknown = guide;
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i]!;
    if (typeof node !== 'object' || node === null || Array.isArray(node)) {
      throw new Error(`guided-text: path "${pathStr}" does not resolve (at "${seg.name}")`);
    }
    const record = node as Record<string, unknown>;
    let next: unknown = record[seg.name];
    if (seg.selector !== undefined) {
      if (!Array.isArray(next)) {
        throw new Error(`guided-text: path "${pathStr}": "${seg.name}" is not an array`);
      }
      next = isIndexSelector(seg.selector)
        ? next[Number(seg.selector)]
        : next.find((item) => (item as { id?: string })?.id === seg.selector);
      if (next === undefined) {
        throw new Error(`guided-text: path "${pathStr}": no item "${seg.selector}" in "${seg.name}"`);
      }
    }
    if (i === segments.length - 1) {
      if (seg.selector !== undefined && isIndexSelector(seg.selector)) {
        // Final segment addresses an array element directly (e.g. cautions[1]).
        (record[seg.name] as unknown[])[Number(seg.selector)] = text;
      } else if (seg.selector !== undefined) {
        throw new Error(`guided-text: path "${pathStr}" ends on an id-selected item, not a string field`);
      } else {
        if (typeof record[seg.name] !== 'string') {
          throw new Error(`guided-text: path "${pathStr}" does not address a string field`);
        }
        record[seg.name] = text;
      }
      return;
    }
    node = next;
  }
}

// ---------------------------------------------------------------------------
// TypeScript AST resolution + drop-in rewrite of the guide modules
// ---------------------------------------------------------------------------

function unwrapExpression(expr: ts.Expression): ts.Expression {
  let e = expr;
  while (
    ts.isAsExpression(e) ||
    ts.isSatisfiesExpression(e) ||
    ts.isParenthesizedExpression(e) ||
    ts.isTypeAssertionExpression(e)
  ) {
    e = e.expression;
  }
  return e;
}

function propertyInitializer(
  obj: ts.ObjectLiteralExpression,
  name: string,
): ts.Expression | undefined {
  for (const prop of obj.properties) {
    if (!ts.isPropertyAssignment(prop)) continue;
    const n = prop.name;
    const propName = ts.isIdentifier(n) || ts.isStringLiteral(n) ? n.text : undefined;
    if (propName === name) return unwrapExpression(prop.initializer);
  }
  return undefined;
}

const isStringy = (node: ts.Node): node is ts.StringLiteral | ts.NoSubstitutionTemplateLiteral =>
  ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node);

/** Find the top-level exported object literal whose `id` property equals `guideId`. */
export function locateGuideObject(
  sourceFile: ts.SourceFile,
  guideId: string,
): ts.ObjectLiteralExpression | undefined {
  for (const stmt of sourceFile.statements) {
    if (!ts.isVariableStatement(stmt)) continue;
    for (const decl of stmt.declarationList.declarations) {
      if (!decl.initializer) continue;
      const init = unwrapExpression(decl.initializer);
      if (!ts.isObjectLiteralExpression(init)) continue;
      const idInit = propertyInitializer(init, 'id');
      if (idInit && isStringy(idInit) && idInit.text === guideId) return init;
    }
  }
  return undefined;
}

/** Resolve a guided path to the string-literal node inside a guide object literal. */
export function resolveStringLiteral(
  guideObject: ts.ObjectLiteralExpression,
  pathStr: string,
): ts.StringLiteral | ts.NoSubstitutionTemplateLiteral {
  const segments = parseGuidedPath(pathStr);
  let node: ts.Expression = guideObject;
  for (const seg of segments) {
    if (!ts.isObjectLiteralExpression(node)) {
      throw new Error(`guided-text: path "${pathStr}": expected an object literal at "${seg.name}"`);
    }
    let next = propertyInitializer(node, seg.name);
    if (!next) {
      throw new Error(`guided-text: path "${pathStr}": property "${seg.name}" not found in source`);
    }
    if (seg.selector !== undefined) {
      if (!ts.isArrayLiteralExpression(next)) {
        throw new Error(`guided-text: path "${pathStr}": "${seg.name}" is not an array literal`);
      }
      const elements = next.elements.map(unwrapExpression);
      let found: ts.Expression | undefined;
      if (isIndexSelector(seg.selector)) {
        found = elements[Number(seg.selector)];
      } else {
        found = elements.find((el) => {
          if (!ts.isObjectLiteralExpression(el)) return false;
          const idInit = propertyInitializer(el, 'id');
          return !!idInit && isStringy(idInit) && idInit.text === seg.selector;
        });
      }
      if (!found) {
        throw new Error(
          `guided-text: path "${pathStr}": no element "${seg.selector}" in "${seg.name}"`,
        );
      }
      next = found;
    }
    node = next;
  }
  if (!isStringy(node)) {
    throw new Error(`guided-text: path "${pathStr}" does not resolve to a string literal`);
  }
  return node;
}

/** Read the current source text at a path (used for post-write verification and tests). */
export function readGuideStringAtPath(sourceText: string, guideId: string, pathStr: string): string {
  const sf = ts.createSourceFile('guide.ts', sourceText, ts.ScriptTarget.Latest, true);
  const obj = locateGuideObject(sf, guideId);
  if (!obj) throw new Error(`guided-text: guide "${guideId}" not found in source`);
  return resolveStringLiteral(obj, pathStr).text;
}

function escapeSingleQuoted(text: string): string {
  return (
    "'" +
    text
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "\\'")
      .replace(/\r/g, '')
      .replace(/\n/g, '\\n')
      .replace(/\u2028/g, '\\u2028')
      .replace(/\u2029/g, '\\u2029') +
    "'"
  );
}

export interface GuideTextChange {
  path: string;
  text: string;
}

/**
 * Apply text changes to a guide module's source, replacing ONLY the addressed
 * string literals (single-quoted, matching the codebase style). Everything
 * else — ids, comments, formatting — is untouched. Throws (writing nothing)
 * if any path fails to resolve.
 */
export function rewriteGuideText(
  sourceText: string,
  guideId: string,
  changes: readonly GuideTextChange[],
): string {
  const sf = ts.createSourceFile('guide.ts', sourceText, ts.ScriptTarget.Latest, true);
  const obj = locateGuideObject(sf, guideId);
  if (!obj) throw new Error(`guided-text: guide "${guideId}" not found in source`);

  const edits = changes.map((change) => {
    const literal = resolveStringLiteral(obj, change.path);
    return {
      start: literal.getStart(sf),
      end: literal.getEnd(),
      replacement: escapeSingleQuoted(change.text),
    };
  });

  // Apply back-to-front so earlier spans stay valid.
  edits.sort((a, b) => b.start - a.start);
  let out = sourceText;
  for (const edit of edits) {
    out = out.slice(0, edit.start) + edit.replacement + out.slice(edit.end);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Locating guide modules on disk
// ---------------------------------------------------------------------------

/** Map every guide id found in `guidesDir` (top-level exported object literals) to its file. */
export function indexGuideFiles(guidesDir: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const name of fs.readdirSync(guidesDir).sort()) {
    if (!name.endsWith('.ts')) continue;
    const filePath = path.join(guidesDir, name);
    const sourceText = fs.readFileSync(filePath, 'utf8');
    const sf = ts.createSourceFile(name, sourceText, ts.ScriptTarget.Latest, true);
    for (const stmt of sf.statements) {
      if (!ts.isVariableStatement(stmt)) continue;
      for (const decl of stmt.declarationList.declarations) {
        if (!decl.initializer) continue;
        const init = unwrapExpression(decl.initializer);
        if (!ts.isObjectLiteralExpression(init)) continue;
        const idInit = propertyInitializer(init, 'id');
        if (idInit && isStringy(idInit)) map.set(idInit.text, filePath);
      }
    }
  }
  return map;
}
